# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joe/src/Super-Deduper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joe/src/Super-Deduper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joe/src/Super-Deduper/CMakeFiles /home/joe/src/Super-Deduper/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joe/src/Super-Deduper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named super_deduper

# Build rule for target.
super_deduper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 super_deduper
.PHONY : super_deduper

# fast build rule for target.
super_deduper/fast:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/build
.PHONY : super_deduper/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named valgrind

# Build rule for target.
valgrind: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 valgrind
.PHONY : valgrind

# fast build rule for target.
valgrind/fast:
	$(MAKE) -f CMakeFiles/valgrind.dir/build.make CMakeFiles/valgrind.dir/build
.PHONY : valgrind/fast

source/argCollector.o: source/argCollector.cpp.o
.PHONY : source/argCollector.o

# target to build an object file
source/argCollector.cpp.o:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/argCollector.cpp.o
.PHONY : source/argCollector.cpp.o

source/argCollector.i: source/argCollector.cpp.i
.PHONY : source/argCollector.i

# target to preprocess a source file
source/argCollector.cpp.i:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/argCollector.cpp.i
.PHONY : source/argCollector.cpp.i

source/argCollector.s: source/argCollector.cpp.s
.PHONY : source/argCollector.s

# target to generate assembly for a file
source/argCollector.cpp.s:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/argCollector.cpp.s
.PHONY : source/argCollector.cpp.s

source/binarySearch.o: source/binarySearch.cpp.o
.PHONY : source/binarySearch.o

# target to build an object file
source/binarySearch.cpp.o:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/binarySearch.cpp.o
.PHONY : source/binarySearch.cpp.o

source/binarySearch.i: source/binarySearch.cpp.i
.PHONY : source/binarySearch.i

# target to preprocess a source file
source/binarySearch.cpp.i:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/binarySearch.cpp.i
.PHONY : source/binarySearch.cpp.i

source/binarySearch.s: source/binarySearch.cpp.s
.PHONY : source/binarySearch.s

# target to generate assembly for a file
source/binarySearch.cpp.s:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/binarySearch.cpp.s
.PHONY : source/binarySearch.cpp.s

source/fileHelper.o: source/fileHelper.cpp.o
.PHONY : source/fileHelper.o

# target to build an object file
source/fileHelper.cpp.o:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/fileHelper.cpp.o
.PHONY : source/fileHelper.cpp.o

source/fileHelper.i: source/fileHelper.cpp.i
.PHONY : source/fileHelper.i

# target to preprocess a source file
source/fileHelper.cpp.i:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/fileHelper.cpp.i
.PHONY : source/fileHelper.cpp.i

source/fileHelper.s: source/fileHelper.cpp.s
.PHONY : source/fileHelper.s

# target to generate assembly for a file
source/fileHelper.cpp.s:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/fileHelper.cpp.s
.PHONY : source/fileHelper.cpp.s

source/fileWriter.o: source/fileWriter.cpp.o
.PHONY : source/fileWriter.o

# target to build an object file
source/fileWriter.cpp.o:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/fileWriter.cpp.o
.PHONY : source/fileWriter.cpp.o

source/fileWriter.i: source/fileWriter.cpp.i
.PHONY : source/fileWriter.i

# target to preprocess a source file
source/fileWriter.cpp.i:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/fileWriter.cpp.i
.PHONY : source/fileWriter.cpp.i

source/fileWriter.s: source/fileWriter.cpp.s
.PHONY : source/fileWriter.s

# target to generate assembly for a file
source/fileWriter.cpp.s:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/fileWriter.cpp.s
.PHONY : source/fileWriter.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/readInfo.o: source/readInfo.cpp.o
.PHONY : source/readInfo.o

# target to build an object file
source/readInfo.cpp.o:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/readInfo.cpp.o
.PHONY : source/readInfo.cpp.o

source/readInfo.i: source/readInfo.cpp.i
.PHONY : source/readInfo.i

# target to preprocess a source file
source/readInfo.cpp.i:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/readInfo.cpp.i
.PHONY : source/readInfo.cpp.i

source/readInfo.s: source/readInfo.cpp.s
.PHONY : source/readInfo.s

# target to generate assembly for a file
source/readInfo.cpp.s:
	$(MAKE) -f CMakeFiles/super_deduper.dir/build.make CMakeFiles/super_deduper.dir/source/readInfo.cpp.s
.PHONY : source/readInfo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... super_deduper"
	@echo "... test"
	@echo "... valgrind"
	@echo "... source/argCollector.o"
	@echo "... source/argCollector.i"
	@echo "... source/argCollector.s"
	@echo "... source/binarySearch.o"
	@echo "... source/binarySearch.i"
	@echo "... source/binarySearch.s"
	@echo "... source/fileHelper.o"
	@echo "... source/fileHelper.i"
	@echo "... source/fileHelper.s"
	@echo "... source/fileWriter.o"
	@echo "... source/fileWriter.i"
	@echo "... source/fileWriter.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/readInfo.o"
	@echo "... source/readInfo.i"
	@echo "... source/readInfo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

