####################################################
#     /  |/  /___ _/ /_____  / __(_) /__ 
#    / /|_/ / __ `/ //_/ _ \/ /_/ / / _ \
#   / /  / / /_/ / ,< /  __/ __/ / /  __/
#  /_/  /_/\__,_/_/|_|\___/_/ /_/_/\___/ 
#
#
# This Makefile is for testing Super-Deduper
# in all of it's default settings.
# We are using an outside python script 
# 
# This is the simplest Makefile in 
# existence.

pyScript=testSD.py
default:
		python $(pyScript)
